<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<OutputType>Library</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>NumericSelectorLib</AssemblyName>
		<RootNamespace>NumericSelectorLib</RootNamespace>
		<Authors>Jorge Rogelio Zir</Authors>
		<Description>Control deslizante numérico con rango limitado y etiquetas personalizadas.</Description>
	</PropertyGroup>
	<ItemGroup>
	  <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>
</Project>
